### ISSUE TITLE
TLS certificate error: wrong domain

### ISSUE THREAD

**Issue by tpltnt** [nannou-org/website#1]
Hi there,

the (new) website [nannou.cc](https://nannou.cc/) yields `SSL_ERROR_BAD_CERT_DOMAIN` since the certificate is only vaild for "*.netlify.com" and "netlify.com".

Cheers,
tpltnt

**Comment by mitchmindtree** [comment]
Thanks for the report!

From what @JoshuaBatty has told me I think this is a matter of waiting for the netlify https support to propagate which can take up to 24 hrs. If this is still occurring tomorrow we'll start investigating and see if we can find out what's going on.

**Comment by JoshuaBatty** [comment]
Thanks @tpltnt i'm aware of this issue, as @mitchmindtree stated, if this isn't resolved in 24 hours i'll start looking into the problem. Feel free to let me know of any other issues you encounter though.

**Comment by JoshuaBatty** [comment]
closing: this has been resolved
