### ISSUE TITLE
Add syntax highlighting for rust code snippets in markdown renders

### ISSUE THREAD

**Issue by mitchmindtree** [nannou-org/website#3]
At the moment the markdown code snippet formatting doesn't seem to support any syntax highlighting, and the black on gray colour scheme feels a bit bland. Maybe there's a plugin available for adding support? Otherwise, it might be possible to embed Github gists that do this for now, but I think they also add annoying github branding to each snippet.

**Comment by JoshuaBatty** [comment]
We are using prism.js in the site now which takes care of all syntax highlighting needs :)
