### ISSUE TITLE
make website (more) accessible via WCAG

### ISSUE THREAD

**Issue by tpltnt** [nannou-org/website#5]
Hi there,

i just tested nannou.cc using the [web accessibilty checker](https://achecker.ca/checker/index.php) and there seem to be some issues to make the website more inclusive. (see also [W3C: WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/))

Cheers,
tpltnt

**Comment by JoshuaBatty** [comment]
Thanks for opening this issue @tpltnt 

I've worked through all the suggestions and now everything seems ok.
